const palavras = [
  { palavra: "bússola", dica: "instrumento que aponta o norte" },
  { palavra: "caverna", dica: "gruta natural subterrânea" },
  { palavra: "mistério", dica: "algo que não foi explicado" },
  { palavra: "deserto", dica: "lugar muito seco e quente" },
  { palavra: "geleira", dica: "grande bloco de gelo natural" },
  { palavra: "sombra", dica: "forma escura criada pela luz" },
  { palavra: "espelho", dica: "reflete a imagem" },
  { palavra: "búfalo", dica: "animal forte com chifres" },
  { palavra: "ilha", dica: "terra cercada por água" },
  { palavra: "nuvem", dica: "conjunto de vapor no céu" },
  { palavra: "ponte", dica: "liga dois lugares separados" },
  { palavra: "vela", dica: "usada para iluminar sem eletricidade" },
  { palavra: "livro", dica: "objeto com páginas para leitura" },
  { palavra: "feitiço", dica: "magia lançada sobre algo ou alguém" },
  { palavra: "búzio", dica: "concha encontrada na praia" },
  { palavra: "trilho", dica: "onde o trem passa" },
  { palavra: "rocha", dica: "grande pedra natural" },
  { palavra: "papiro", dica: "antigo material para escrita" },
  { palavra: "túnel", dica: "passagem por dentro da terra" },
  { palavra: "faísca", dica: "pequeno brilho do fogo" },
  { palavra: "eco", dica: "som repetido" },
  { palavra: "bruma", dica: "névoa leve ou fumaça" },
  { palavra: "búzio", dica: "concha em forma espiral" },
  { palavra: "mapa", dica: "representação de um lugar" },
  { palavra: "navio", dica: "grande embarcação" },
  { palavra: "enigma", dica: "algo que precisa ser decifrado" },
  { palavra: "relógio", dica: "mostra as horas" },
  { palavra: "segredo", dica: "algo que não deve ser contado" },
  { palavra: "torre", dica: "estrutura alta e estreita" },
  { palavra: "búzio", dica: "objeto do mar em forma de espiral" },
  { palavra: "cratera", dica: "buraco causado por impacto" },
  { palavra: "tempo", dica: "pode ser o clima ou a duração" },
  { palavra: "vento", dica: "ar em movimento" },
  { palavra: "corda", dica: "usada para amarrar coisas" },
  { palavra: "pedra", dica: "objeto duro da natureza" },
  { palavra: "viagem", dica: "ato de ir a outro lugar" },
  { palavra: "chave", dica: "abre portas ou cadeados" },
  { palavra: "baú", dica: "onde se guardam tesouros" },
  { palavra: "folha", dica: "parte da planta" },
  { palavra: "brilho", dica: "luz intensa" },
  { palavra: "vento", dica: "movimento do ar" },
  { palavra: "seguro", dica: "protegido contra perigo" },
  { palavra: "norte", dica: "ponto cardeal de orientação" },
  { palavra: "poço", dica: "buraco fundo com água" },
  { palavra: "vento", dica: "ar em movimento" },
  { palavra: "clima", dica: "tempo típico de um lugar" },
  { palavra: "bússola", dica: "usada para encontrar direção" },
  { palavra: "trilha", dica: "caminho estreito na natureza" },
  { palavra: "canoa", dica: "barco pequeno e leve" },
  { palavra: "rede", dica: "usada para pescar ou deitar" }
];
