const palavras = [{ palavra: "astrolábio", dica: "instrumento antigo usado para observar estrelas" },
  { palavra: "quimera", dica: "criatura mítica ou ideia fantasiosa" },
  { palavra: "metáfora", dica: "figura de linguagem que compara indiretamente" },
  { palavra: "criptografia", dica: "técnica de escrita secreta" },
  { palavra: "labirinto", dica: "estrutura com caminhos confusos" },
  { palavra: "glacial", dica: "extremamente frio ou relacionado a gelo" },
  { palavra: "nebulosa", dica: "nuvem de poeira no espaço" },
  { palavra: "efêmero", dica: "dura pouco tempo" },
  { palavra: "pêndulo", dica: "objeto oscilante usado em relógios" },
  { palavra: "fóssil", dica: "resto preservado de um ser antigo" },
  { palavra: "hercúleo", dica: "extremamente difícil ou exigente" },
  { palavra: "filantropo", dica: "pessoa que ajuda os outros" },
  { palavra: "alcateia", dica: "grupo de lobos" },
  { palavra: "sarcófago", dica: "caixão usado no Egito antigo" },
  { palavra: "etéreo", dica: "relacionado ao céu ou ao irreal" },
  { palavra: "cripta", dica: "câmara subterrânea em igrejas" },
  { palavra: "dodecaedro", dica: "sólido com 12 faces" },
  { palavra: "procrastinar", dica: "adiar tarefas" },
  { palavra: "enigma", dica: "algo misterioso ou difícil de entender" },
  { palavra: "constelação", dica: "conjunto de estrelas com forma" },
  { palavra: "arqueólogo", dica: "estuda civilizações antigas" },
  { palavra: "estalactite", dica: "formação que desce do teto em cavernas" },
  { palavra: "cosmogonia", dica: "teoria sobre a origem do universo" },
  { palavra: "epifania", dica: "revelação súbita ou iluminação" },
  { palavra: "algoritmo", dica: "sequência lógica de passos" },
  { palavra: "aurora", dica: "fenômeno luminoso polar" },
  { palavra: "catacumba", dica: "galeria subterrânea usada como sepultura" },
  { palavra: "neologismo", dica: "palavra inventada ou recente" },
  { palavra: "obscuro", dica: "difícil de entender ou ver" },
  { palavra: "axioma", dica: "verdade aceita sem provas" },
  { palavra: "reticente", dica: "que evita dizer tudo" },
  { palavra: "anacronismo", dica: "erro de tempo histórico" },
  { palavra: "corrosivo", dica: "capaz de destruir aos poucos" },
  { palavra: "sintaxe", dica: "ordem das palavras na frase" },
  { palavra: "paradoxo", dica: "ideia contraditória mas lógica" },
  { palavra: "idiossincrasia", dica: "característica única de alguém" },
  { palavra: "plutocracia", dica: "governo controlado pelos ricos" },
  { palavra: "onomatopeia", dica: "palavra que imita som" },
  { palavra: "penumbra", dica: "meia sombra ou luz fraca" },
  { palavra: "cósmico", dica: "relativo ao universo" },
  { palavra: "mnemônico", dica: "ajuda para lembrar algo" },
  { palavra: "ubíquo", dica: "presente em todos os lugares" },
  { palavra: "atavismo", dica: "traço antigo que reaparece" },
  { palavra: "perene", dica: "dura por muito tempo" },
  { palavra: "quimérico", dica: "fantasioso ou irreal" },
  { palavra: "mitocôndria", dica: "parte da célula que gera energia" },
  { palavra: "vórtice", dica: "movimento circular, como redemoinho" },
  { palavra: "axiológico", dica: "relativo a valores e ética" },
  { palavra: "inóspito", dica: "hostil ou difícil de habitar" },
  { palavra: "elucidar", dica: "tornar claro ou explicar" }
];